routes/web.php
    <?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Auth;

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home1');

    Auth::routes();

    Route::group(['middleware' => ['web', 'checkAuth']], function(){
        Route::get('user/profile', 'UserController@profile')->name('user.profile');
        Route::patch('user/{id}/change', 'UserController@changeProfile');
        Route::get('user/data', 'UserController@listData')->name('user.data');
        Route::resource('user', 'UserController');

        Route::get('/home/inventory', 'HomeController@listData')->name('home.inventory');

        Route::get('transaction/new', 'SalesDetailController@newSession')->name('transaction.new');
        Route::get('transaction/{id}/data', 'SalesDetailController@listData')->name('transaction.data');
        Route::get('transaction/printnote', 'SalesDetailController@printNote')->name('transaction.print');
        Route::get('transaction/notepdf', 'SalesDetailController@notePDF')->name('transaction.pdf');
        Route::get('transaction/return', 'SalesDetailController@return')->name('transaction.return');
        Route::post('transaction/save', 'SalesDetailController@saveData');
        Route::post('transaction/wholesale', 'SalesDetailController@wholesale');
        Route::post('transaction/admincheck', 'SalesDetailController@admincheck');
        Route::post('transaction/return/{id}', 'SalesDetailController@returnID')->name('transaction.returnID');
        Route::post('transaction/returnConfirm', 'SalesDetailController@returnConfirm')->name('transaction.returnConfirm');
        Route::post('transaction/returnSubmit', 'SalesDetailController@returnSubmit')->name('transaction.returnSubmit');
        Route::post('transaction/addCustomProduct', 'SalesDetailController@addCustomProduct')->name('transaction.addCustomProduct');
        Route::get('transaction/return/{id}/data', 'SalesDetailController@returnData')->name('transaction.returnData');
        Route::get('transaction/loadform/{discount}/{total}/{received}/{id}', 'SalesDetailController@loadForm');
        Route::resource('transaction', 'SalesDetailController');
    });

    Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
        Route::get('category/data', 'CategoryController@listData')->name('category.data');
        Route::resource('category', 'CategoryController');

        Route::get('product/data', 'ProductController@listData')->name('product.data');
        Route::get('product/dataReceived', 'ProductController@listDataReceived')->name('product.data.received');
        Route::get('product/dataTransfered', 'ProductController@listDataTransfered')->name('product.data.transfered');
        Route::post('product/delete', 'ProductController@deleteSelected');
        Route::post('product/print', 'ProductController@printBarcode');
        Route::post('product/upload', 'ProductController@uploadProducts')->name('product.upload');
        Route::post('product/export', 'ProductController@exportProducts')->name('product.export');
        Route::get('product/export-inventory', 'ProductController@exportInventory')->name('product.export-inventory');
        Route::resource('product', 'ProductController');

        Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
        Route::resource('supplier', 'SupplierController');

        Route::get('member/data', 'MemberController@listData')->name('member.data');
        Route::post('member/print', 'MemberController@printCard');
        Route::resource('member', 'MemberController');

        Route::get('expenditure/data', 'ExpenditureController@listData')->name('expenditure.data');
        Route::resource('expenditure', 'ExpenditureController');

        Route::get('purchase/data', 'PurchaseController@listData')->name('purchase.data');
        Route::get('purchase/{id}/add', 'PurchaseController@create');
        Route::get('purchase/{id}/lihat', 'PurchaseController@show');
        Route::resource('purchase', 'PurchaseController');   

        Route::get('purchase_detail/{id}/data', 'PurchaseDetailController@listData')->name('purchase_detail.data');
        Route::get('purchase_detail/loadform/{diskon}/{total}', 'PurchaseDetailController@loadForm');
        Route::resource('purchase_detail', 'PurchaseDetailController');   

        Route::get('sales/data', 'SalesController@listData')->name('sales.data');
        Route::get('sales/dataReturn', 'SalesController@listDataReturn')->name('sales.dataReturn');
        Route::get('sales/{id}/show', 'SalesController@show');
        Route::resource('sales', 'SalesController');

        Route::get('reporting', 'ReportingController@index')->name('reporting.index');
        Route::post('reporting', 'ReportingController@refresh')->name('reporting.refresh');
        Route::get('reporting/data/{start}/{end}', 'ReportingController@listData')->name('reporting.data'); 
        Route::get('reporting/pdf/{start}/{end}', 'ReportingController@exportPDF');

        Route::resource('setting', 'SettingController');

        Route::get('receiving/data', 'ReceivingController@listData')->name('receiving.data');
        Route::post('receiving/new', 'ReceivingController@newSession')->name('receiving.new');
        Route::post('receiving/clear', 'ReceivingController@clearSession')->name('receiving.clear');
        Route::resource('receiving', 'ReceivingController');

        Route::get('transfer/data', 'TransferController@listData')->name('transfer.data');
        Route::get('transfer/newData', 'TransferController@listNewData')->name('transfer.newData');
        Route::post('transfer/new', 'TransferController@newSession')->name('transfer.new');
        Route::get('transfer/notepdf', 'TransferController@notePDF')->name('transfer.pdf');
        Route::any('transfer/clearSession', 'TransferController@clearSession')->name('transfer.clearSession');
        Route::resource('transfer', 'TransferController');

        Route::get('branch/data', 'BranchController@listData')->name('branch.data');
        Route::resource('branch', 'BranchController');
    });

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'product';
    protected $primaryKey = 'product_id';
    
    public function category(){
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Support\Facades\Auth;
use PDF;
use App\Product;
use App\Inventory;
use App\ReceivingDetails;
use App\TransferDetails;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();    
        $user = Auth::user();  
        return view('product.index', compact('category','user'));
    }

    public function listData()
    {
        $user = Auth::user();
        $product = Product::select('product.*', 'category.category', 'inventory.cost', 'inventory.discount', 'inventory.price', 'inventory.wholesaleprice', 'inventory.stock')->leftJoin('category', 'category.category_id', '=', 'product.category_id')->leftJoin('inventory', 'inventory.product_code', '=', 'product.product_code')->orderBy('product.created_at', 'desc')->get();
        
        $no = 0;
        $data = array();
        foreach($product as $list){
            $no ++;
            $row = array();
            $buttons = "<div class='btn-group'>
            <a onclick='editForm(".$list->product_id.")' class='btn btn-primary btn-sm'><i class='fa fa-pencil'></i></a>";
            
            if ($user->level == 0) {
                $buttons .= "<a onclick='deleteData(".$list->product_id.")' class='btn btn-danger btn-sm'><i class='fa fa-trash'></i></a>";
            }
            
            $row[] = "<input type='checkbox' name='id[]'' value='".$list->product_id."'>";
            $row[] = $no;
            $row[] = $list->product_code;
            $row[] = $list->product_name;
            $row[] = $list->category;
            $row[] = $list->brand;
            $row[] = "PhP ".format_money($list->cost);
            $row[] = "PhP ".format_money($list->price);
            $row[] = "PhP ".format_money($list->wholesaleprice);
            $row[] = $list->stock;
            $row[] = $list->stock_limit;
            $row[] = $buttons.
                    "</div>";
            $data[] = $row;
        }
        
        $output = array("data" => $data);
        return response()->json($output);
    }

    public function listDataReceived()
    {
        $product = ReceivingDetails::select('receive_details.*', 'product.product_name', 'product.brand', 'branch.name', 'received.from_branch_id')->leftJoin('product', 'receive_details.product_code', '=', 'product.product_code')->leftJoin('category', 'category.category_id', '=', 'product.category_id')->leftJoin('received', 'received.id', '=', 'receive_details.receive_id')->leftJoin('branch', 'received.from_branch_id', '=', 'branch.id')->orderBy('receive_details.updated_at', 'desc')->get();
        
        $no = 0;
        $data = [];
        foreach($product as $list){
            $row = [];
            $row[] = $list->product_code;
            $row[] = $list->product_name;
            $row[] = $list->category;
            $row[] = $list->brand;
            $row[] = $list->name;
            $row[] = $list->quantity;
            $data[] = $row;
        }
        
        return response()->json(["data" => $data]);
    }

    public function listDataTransfered()
    {
        $product = TransferDetails::select('transfer_details.*', 'product.product_name', 'product.brand', 'branch.name', 'transfer.to_branch_id')->leftJoin('product', 'transfer_details.product_code', '=', 'product.product_code')->leftJoin('category', 'category.category_id', '=', 'product.category_id')->leftJoin('transfer', 'transfer.id', '=', 'transfer_details.transfer_id')->leftJoin('branch', 'transfer.to_branch_id', '=', 'branch.id')->orderBy('transfer_details.updated_at', 'desc')->get();
        
        $no = 0;
        $data = [];
        foreach($product as $list){
            $row = [];
            $row[] = $list->product_code;
            $row[] = $list->product_name;
            $row[] = $list->category;
            $row[] = $list->brand;
            $row[] = $list->name;
            $row[] = $list->quantity;
            $data[] = $row;
        }
        
        return response()->json(["data" => $data]);
    }

    public function store(Request $request)
    {
        $product = Product::where('product_code', '=', $request['code'])->count();
        if($product < 1){
            $product = new Product;
            $product->product_code   = $request['code'];
            $product->product_name   = $request['name'];
            $product->category_id    = $request['category'];
            $product->brand          = (isset($request['brand'])) ? $request['brand'] : " ";
            $product->stock_limit    = $request['stock_limit'];
            $product->save();

            $inventory = new Inventory;
            $inventory->product_code   = $request['code'];
            $inventory->cost           = $request['cost'];
            $inventory->wholesaleprice = $request['wholesaleprice'];
            $inventory->price          = $request['price'];
            $inventory->stock          = $request['stock'];
            $inventory->branch_code = env('BRANCH_CODE');
            $inventory->save();

            echo json_encode(array('msg'=>'success'));
        }else{
            echo json_encode(array('msg'=>'error'));
        }
    }
    
    public function edit($id)
    {
        $product = Product::select('product.*', 'inventory.stock', 'inventory.wholesaleprice', 'inventory.cost', 'inventory.price' )->leftJoin('inventory', 'inventory.product_code', '=', 'product.product_code')->where('product.product_id',$id)->first();
        echo json_encode(['data' => $product, 'user' => Auth::user()]);
    }

    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->product_name   = $request['name'];
        $product->category_id    = $request['category'];
        $product->brand          = $request['brand'];
        $product->stock_limit    = $request['stock_limit'];
        $product->update();

        $inventory = Inventory::where('product_code', $product->product_code)->first();
        $inventory->cost           = $request['cost'];
        $inventory->wholesaleprice = $request['wholesaleprice'];
        $inventory->price          = $request['price'];
        $inventory->stock          = $request['stock'];
        $inventory->update();

        echo json_encode(array('msg'=>'success'));
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        
        if (!$product)
        {
            $inventory = Inventory::where('product_code', $product->product_code)->first();
        
            if (!$inventory)
            {
                $inventory->delete();
            }
        }

        $product->delete();
    }

    public function deleteSelected(Request $request)
    {
        foreach($request['id'] as $id){
            $product = Product::find($id);
            $product->delete();
        }
    }

    public function show(Request $request){}

    public function printBarcode(Request $request)
    {
        $dataproduct = array();
        foreach($request['id'] as $id){
            $product = Product::select('product.*', 'inventory.*' )->leftJoin('inventory', 'inventory.product_code', '=', 'product.product_code')->where('product_id', $id)->first();
            $dataproduct[] = $product;
        }
        $no = 1;
        $pdf = PDF::loadView('product.barcode', compact('dataproduct', 'no'));
        $pdf->setPaper('a4', 'potrait');      
        return $pdf->stream();
    }

    public function uploadProducts(Request $request)
    {
        $file_handle = fopen($request->file('fileupload')->path(), 'r');
        $count = 0;
        $errorCount = -1;

        while (!feof($file_handle)) 
        {
            $values = fgetcsv($file_handle, 0, ",");

            if (!empty($values))
            {
                if ($values <= 1) 
                {
                    return redirect()->route('product.index', ["error" => "File format not allowed | File should be CSV (Comma delimeted)", "success" => 0] );
                }

                $product_code = ltrim(ltrim(is_numeric($values[0]) ? number_format($values[0],0,'','') : $values[0] ,"0")," ");
                $title = ltrim($this->slug($values[1])," ");
                $description = ltrim($values[2]," ");
                $brand = ltrim(strtoupper($values[3])," ");
                $category = ltrim(strtoupper($values[4])," ");
                $cost = floatval($values[5]);
                $price = floatval($values[6]);
                $wholesale = floatval( (isset($values[7]) && $values[7] > 0) ? $values[7] : $values[6] );
                $stock = floatval( (isset($values[8]) && $values[8] > 0) ? $values[8] : 0 );

                try 
                {
                    if ( $product_code != "" && $title != "" && $category != "" && $cost > 0 && $price > 0 )
                    {
                        $categoryData = Category::where('category', $category)->first();

                        if (!$categoryData)
                        {
                            $categoryData = new Category;
                            $categoryData->category = $category;
                            $categoryData->save();
                        }

                        $product = Product::where('product_code',$product_code)->first();

                        if (!$product)
                        {
                            $product = new Product;
                        }

                        $product->product_code = $product_code;
                        $product->category_id = $categoryData->category_id;
                        $product->product_name = $title;
                        $product->brand = $brand;
                        $product->save();
                        

resources/views/product/barcode.blade.php
<!DOCTYPE html>
<html>
<head>
   <title>Print Barcode</title>
</head>
<body>
   <table width="100%">   
     <tr>
      
      @foreach($dataproduct as $data)
      <td align="center" style="border: 1px solid #ccc">
      {{ $data->product_name}} - PhP {{ format_money($data->price) }}</span><br><br>
      <img src="data:image/png;base64,{{ DNS1D::getBarcodePNG( $data->product_code, 'C39') }}" height="60" width="180">
      <br>{{ $data->product_code}}
      </td>
      @if( $no++ % 3 == 0)
         </tr><tr>
      @endif
     @endforeach
     
     </tr>
   </table>
</body>
</html>

resources/views/product/index.blade.php
@extends('layouts.app')

@section('title')
Product List
@endsection

@section('breadcrumb')
@parent
<li>product</li>
@endsection

@section('content')
<style>
    .file {
        position: relative;
        overflow: hidden;
    }

    .file input {
        position: absolute;
        font-size: 50px;
        opacity: 0;
        right: 0;
        top: 0;
    }

</style>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            @if(isset($error))
                <div class="alert alert-warning" id="success-alert">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    @if(floatval($error) >= 0 )
                        <strong>Uplead complete! </strong> A total of {{ $success }} product SKU's have been uploaded
                        and a total of {{ $error }} SKU's were unsuccessful
                    @else
                        <strong>Error! </strong> {{ $error }}
                    @endif
                </div>
            @endif

            <div class="box-header">
                <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add</a>
                @if($user->level == 0)
                    <a onclick="deleteAll()" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</a>
                @endif
                <a onclick="printBarcode()" class="btn btn-info"><i class="fa fa-barcode"></i> Print Barcode</a>
                <a onclick="exportProducts()" class="btn btn-primary"><i class="fa fa-sign-out"></i> Export Products</a>
                <a onclick="exportInventory()" class="btn btn-normal"><i class="fa fa-sign-out"></i> Export Inventory Balance</a>

                <div class="file btn btn-lg btn-warning" style="font-size: 15px;">
                    <i class="fa fa-upload"></i>
                    Upload
                    <form class="form-horizontal" method="post" enctype="multipart/form-data" id="fileUp"
                        action="{{ route('product.upload') }}">
                        {{ csrf_field() }} {{ method_field('POST') }}
                        <input type="file" name="fileupload" id="fileupload" multiple />
                    </form>
                </div>
            </div>
            <div class="box-body">
                <form method="post" id="form-product">
                    {{ csrf_field() }}
                    <table class="table table-striped" id="table-product">
                        <thead>
                            <tr>
                                <th width="20"><input type="checkbox" value="1" id="select-all"></th>
                                <th width="20">No</th>
                                <th>Product Code</th>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Brand</th>
                                <th>Cost</th>
                                <th>Price</th>
                                <th>Whole Sale</th>
                                <th>Stock</th>
                                <th>Stock Limit</th>
                                <th width="100">Action</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </form>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3>Recently Received Products</h3>
                        </div>
                        <div class="box-body">
                            <table class="table table-striped" id="table-product-received">
                                <thead>
                                    <tr>
                                        <th>Product Code</th>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Brand</th>
                                        <th>Origin</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3>Recently Transfered Products</h3>
                        </div>
                        <div class="box-body">
                            <table class="table table-striped" id="table-product-transfered">
                                <thead>
                                    <tr>
                                        <th>Product Code</th>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Brand</th>
                                        <th>Destination</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@include('product.form')
@endsection

@section('script')
<script type="text/javascript">
    var table, save_method;
    $(function () {
        table = $('#table-product').DataTable({
            "processing": true,
            "serverside": true,
            "ajax": {
                "url": "{{ route('product.data') }}",
                "type": "GET"
            },
            'columnDefs': [{
                'targets': 0,
                'searchable': false,
                'orderable': false
            }],
            'order': [1, 'asc']
        });

        tableReceived = $('#table-product-received').DataTable({
            "processing": true,
            "serverside": true,
            "ajax": {
                "url": "{{ route('product.data.received') }}",
                "type": "GET"
            },
            'columnDefs': [{
                'targets': 0,
                'searchable': false,
                'orderable': false
            }],
            'order': [1, 'asc']
        });

        tableTransfered = $('#table-product-transfered').DataTable({
            "processing": true,
            "serverside": true,
            "ajax": {
                "url": "{{ route('product.data.transfered') }}",
                "type": "GET"
            },
            'columnDefs': [{
                'targets': 0,
                'searchable': false,
                'orderable': false
            }],
            'order': [1, 'asc']
        });

        $('#fileupload').on("change", function () {
            $('#fileUp').submit();
        });

        $('#select-all').click(function () {
            $('input[type="checkbox"]').prop('checked', this.checked);
        });

        $('#modal-form form').validator().on('submit', function (e) {
            if (!e.isDefaultPrevented()) {
                var id = $('#id').val();
                if (save_method == "add") url = "{{ route('product.store') }}";
                else url = "product/" + id;

                $.ajax({
                    url: url,
                    type: "POST",
                    data: $('#modal-form form').serialize(),
                    dataType: 'JSON',
                    success: function (data) {
                        if (data.msg == "error") {
                            alert('The product code has been used!');
                            $('#code').focus().select();
                        } else {
                            $('#modal-form').modal('hide');
                            table.ajax.reload();
                        }
                    },
                    error: function (xhr, status, error) {
                        alert("Unable to save data!");
                    }
                });
                return false;
            }
        });
    });

    function addForm() {
        save_method = "add";
        $('input[name=_method]').val('POST');
        $('#modal-form').modal('show');
        $('#modal-form form')[0].reset();
        $('.modal-title').text('Add Product');
        $('#code').attr('readonly', false);
    }

    function editForm(id) {
        save_method = "edit";
        $('input[name=_method]').val('PATCH');
        $('#modal-form form')[0].reset();
        $.ajax({
            url: "product/" + id + "/edit",
            type: "GET",
            dataType: "JSON",
            success: function (data) {

                prod = data.data;
                user = data.user;
                $('#modal-form').modal('show');
                $('.modal-title').text('Edit product');

                $('#id').val(prod.product_id);
                $('#code').val(prod.product_code).attr('readonly', true);
                $('#name').val(prod.product_name);
                $('#category').val(prod.category_id);
                $('#brand').val(prod.brand);
                $('#cost').val(prod.cost);
                $('#wholesaleprice').val(prod.wholesaleprice);
                $('#price').val(prod.price);
                $('#stock').val(prod.stock);
                $('#stock_limit').val(prod.stock_limit);

                if (user.level !== 0) {
                    $("#price").prop("disabled", true);
                    $("#wholesaleprice").prop("disabled", true);
                    $("#cost").prop("disabled", true);
                    $("#stock").prop("disabled", true);
                }

            },
            error: function () {
                alert("Cannot display data!");
            }
        });
    }

    function deleteData(id) {
        if (confirm("Are sure the data will be deleted?")) {
            $.ajax({
                url: "product/" + id,
                type: "POST",
                data: {
                    '_method': 'DELETE',
                    '_token': $('meta[name=csrf-token]').attr('content')
                },
                success: function (data) {
                    table.ajax.reload();
                },
                error: function () {
                    alert("Cannot delete data!");
                }
            });
        }
    }

    function deleteAll() {
        if ($('input:checked').length < 1) {
            alert('Select the data to be deleted!');
        } else if (confirm("Are sure to delete all selected data?")) {
            $.ajax({
                url: "product/delete",
                type: "POST",
                data: $('#form-product').serialize(),
                success: function (data) {
                    table.ajax.reload();
                },
                error: function () {
                    alert("Cannot delete data!");
                }
            });
        }
    }

    function printBarcode() {
        if ($('input:checked').length < 1) {
            alert('Select the data to be printed!');
        } else {
            $('#form-product').attr('target', '_blank').attr('action', "product/print").submit();
        }
    }

    function exportProducts() {
        if ($('input:checked').length < 1) {
            alert('Select the data to be exported!');
        } else if (confirm("Are sure to export all selected data?")) {
            $.ajax({
                url: "product/export",
                type: "POST",
                data: $('#form-product').serialize(),
                success: function (data) {
                    var downloadLink = document.createElement("a");
                    var fileData = ['\ufeff'+data];

                    var blobObject = new Blob(fileData,{
                        type: "text/csv;charset=utf-8;"
                    });

                    var url = URL.createObjectURL(blobObject);
                    downloadLink.href = url;
                    downloadLink.download = "products.csv";

                    /*
                    * Actually download CSV
                    */
                    document.body.appendChild(downloadLink);
                    downloadLink.click();
                    document.body.removeChild(downloadLink);
                },
                error: function () {
                    alert("Cannot export data!");
                }
            });
        }
    }

    function exportInventory() {
        
        if (confirm('Confirm export of inventory balance?')) {
            window.location.href = 'product/export-inventory';
        } else {
            console.log('Export canceled.');
        }
    }

</script>
@endsection