routes/web.php
    <?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Auth;

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home1');

    Auth::routes();

    Route::group(['middleware' => ['web', 'checkAuth']], function(){
        Route::get('user/profile', 'UserController@profile')->name('user.profile');
        Route::patch('user/{id}/change', 'UserController@changeProfile');
        Route::get('user/data', 'UserController@listData')->name('user.data');
        Route::resource('user', 'UserController');

        Route::get('/home/inventory', 'HomeController@listData')->name('home.inventory');

        Route::get('transaction/new', 'SalesDetailController@newSession')->name('transaction.new');
        Route::get('transaction/{id}/data', 'SalesDetailController@listData')->name('transaction.data');
        Route::get('transaction/printnote', 'SalesDetailController@printNote')->name('transaction.print');
        Route::get('transaction/notepdf', 'SalesDetailController@notePDF')->name('transaction.pdf');
        Route::get('transaction/return', 'SalesDetailController@return')->name('transaction.return');
        Route::post('transaction/save', 'SalesDetailController@saveData');
        Route::post('transaction/wholesale', 'SalesDetailController@wholesale');
        Route::post('transaction/admincheck', 'SalesDetailController@admincheck');
        Route::post('transaction/return/{id}', 'SalesDetailController@returnID')->name('transaction.returnID');
        Route::post('transaction/returnConfirm', 'SalesDetailController@returnConfirm')->name('transaction.returnConfirm');
        Route::post('transaction/returnSubmit', 'SalesDetailController@returnSubmit')->name('transaction.returnSubmit');
        Route::post('transaction/addCustomProduct', 'SalesDetailController@addCustomProduct')->name('transaction.addCustomProduct');
        Route::get('transaction/return/{id}/data', 'SalesDetailController@returnData')->name('transaction.returnData');
        Route::get('transaction/loadform/{discount}/{total}/{received}/{id}', 'SalesDetailController@loadForm');
        Route::resource('transaction', 'SalesDetailController');
    });

    Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
        Route::get('category/data', 'CategoryController@listData')->name('category.data');
        Route::resource('category', 'CategoryController');

        Route::get('product/data', 'ProductController@listData')->name('product.data');
        Route::get('product/dataReceived', 'ProductController@listDataReceived')->name('product.data.received');
        Route::get('product/dataTransfered', 'ProductController@listDataTransfered')->name('product.data.transfered');
        Route::post('product/delete', 'ProductController@deleteSelected');
        Route::post('product/print', 'ProductController@printBarcode');
        Route::post('product/upload', 'ProductController@uploadProducts')->name('product.upload');
        Route::post('product/export', 'ProductController@exportProducts')->name('product.export');
        Route::get('product/export-inventory', 'ProductController@exportInventory')->name('product.export-inventory');
        Route::resource('product', 'ProductController');

        Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
        Route::resource('supplier', 'SupplierController');

        Route::get('member/data', 'MemberController@listData')->name('member.data');
        Route::post('member/print', 'MemberController@printCard');
        Route::resource('member', 'MemberController');

        Route::get('expenditure/data', 'ExpenditureController@listData')->name('expenditure.data');
        Route::resource('expenditure', 'ExpenditureController');

        Route::get('purchase/data', 'PurchaseController@listData')->name('purchase.data');
        Route::get('purchase/{id}/add', 'PurchaseController@create');
        Route::get('purchase/{id}/lihat', 'PurchaseController@show');
        Route::resource('purchase', 'PurchaseController');   

        Route::get('purchase_detail/{id}/data', 'PurchaseDetailController@listData')->name('purchase_detail.data');
        Route::get('purchase_detail/loadform/{diskon}/{total}', 'PurchaseDetailController@loadForm');
        Route::resource('purchase_detail', 'PurchaseDetailController');   

        Route::get('sales/data', 'SalesController@listData')->name('sales.data');
        Route::get('sales/dataReturn', 'SalesController@listDataReturn')->name('sales.dataReturn');
        Route::get('sales/{id}/show', 'SalesController@show');
        Route::resource('sales', 'SalesController');

        Route::get('reporting', 'ReportingController@index')->name('reporting.index');
        Route::post('reporting', 'ReportingController@refresh')->name('reporting.refresh');
        Route::get('reporting/data/{start}/{end}', 'ReportingController@listData')->name('reporting.data'); 
        Route::get('reporting/pdf/{start}/{end}', 'ReportingController@exportPDF');

        Route::resource('setting', 'SettingController');

        Route::get('receiving/data', 'ReceivingController@listData')->name('receiving.data');
        Route::post('receiving/new', 'ReceivingController@newSession')->name('receiving.new');
        Route::post('receiving/clear', 'ReceivingController@clearSession')->name('receiving.clear');
        Route::resource('receiving', 'ReceivingController');

        Route::get('transfer/data', 'TransferController@listData')->name('transfer.data');
        Route::get('transfer/newData', 'TransferController@listNewData')->name('transfer.newData');
        Route::post('transfer/new', 'TransferController@newSession')->name('transfer.new');
        Route::get('transfer/notepdf', 'TransferController@notePDF')->name('transfer.pdf');
        Route::any('transfer/clearSession', 'TransferController@clearSession')->name('transfer.clearSession');
        Route::resource('transfer', 'TransferController');

        Route::get('branch/data', 'BranchController@listData')->name('branch.data');
        Route::resource('branch', 'BranchController');
    });

app/PurchaseDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PurchaseDetail extends Model
{
    protected $table = 'purchase_detail';
}

app/Http/Controllers/PurchaseDetailController.php
<?php

namespace App\Http\Controllers;

use Redirect;
use App\Purchase;
use App\Supplier;
use App\Product;
use App\PurchaseDetail;
use Illuminate\Http\Request;

class PurchaseDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produk = Produk::all();
        $idpurchase = session('idpurchase');
        $supplier = Supplier::find(session('idsupplier'));
        return view('purchase_detail.index', compact('produk', 'idpurchase', 'supplier'));
    }

    public function listData($id)
    {

        $detail = PurchaseDetail::leftJoin('produk', 'produk.kode_produk', '=', 'purchase_detail.kode_produk')
            ->where('id_purchase', '=', $id)
            ->get();
        $no = 0;
        $data = array();
        $total = 0;
        $total_item = 0;
        foreach($detail as $list){
            $no ++;
            $row = array();
            $row[] = $no;
            $row[] = $list->kode_produk;
            $row[] = $list->nama_produk;
            $row[] = "Rp. ".format_uang($list->harga_beli);
            $row[] = "<input type='number' class='form-control' name='jumlah_$list->id_purchase_detail' value='$list->jumlah' onChange='changeCount($list->id_purchase_detail)'>";
            $row[] = "Rp. ".format_uang($list->harga_beli * $list->jumlah);
            $row[] = '<a onclick="deleteItem('.$list->id_purchase_detail.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>';
            $data[] = $row;

            $total += $list->harga_beli * $list->jumlah;
            $total_item += $list->jumlah;
        }

        $data[] = array("<span class='hide total'>$total</span><span class='hide totalitem'>$total_item</span>", "", "", "", "", "", "");
        
        $output = array("data" => $data);
        return response()->json($output);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produk = Produk::where('kode_produk', '=', $request['kode'])->first();
        $detail = new PurchaseDetail;
        $detail->id_purchase = $request['idpurchase'];
        $detail->kode_produk = $request['kode'];
        $detail->harga_beli = $produk->harga_beli;
        $detail->jumlah = 1;
        $detail->sub_total = $produk->harga_beli;
        $detail->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PembelianDetail  $pembelianDetail
     * @return \Illuminate\Http\Response
     */
    public function show(PurchaseDetail $purchaseDetail)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PembelianDetail  $pembelianDetail
     * @return \Illuminate\Http\Response
     */
    public function edit(PurchaseDetail $purchaseDetail)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PembelianDetail  $pembelianDetail
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nama_input = "price_".$id;
        $detail = PurchaseDetail::find($id);
        $detail->jumlah = $request[$nama_input];
        $detail->sub_total = $detail->harga_beli * $request[$nama_input];
        $detail->update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PurchaseDetail  $pembelianDetail
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $detail = PurchaseDetail::find($id);
        $detail->delete();
    }

    public function loadForm($diskon, $total){
        $bayar = $total - ($diskon / 100 * $total);
        $data = array(
            "totalrp" => format_uang($total),
            "bayar" => $pay,
            "bayarrp" => format_uang($pay),
            "terbilang" => ($pay > 0) ? ucwords( numberTowords( $pay ) ) : "" ." Pesos",
        );
        return response()->json($data);
    }
}

resources/views/purchase_detail/index.blade.php
@extends('layouts.app')

@section('title')
  Purchasing
@endsection

@section('breadcrumb')
   @parent
   <li>purchase</li>
   <li>tambah</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
   
     <div class="box-body">

<table>
  <tr><td width="150">Supplier</td><td><b>{{ $supplier->name }}</b></td></tr>
  <tr><td>Address</td><td><b>{{ $supplier->address }}</b></td></tr>
  <tr><td>Contact</td><td><b>{{ $supplier->phone }}</b></td></tr>
</table>
<hr>

<form class="form form-horizontal form-produk" method="post">
{{ csrf_field() }}
  <input type="hidden" name="idpurchase" value="{{ $idpurchase }}">
  <div class="form-group">
      <label for="kode" class="col-md-2 control-label">Kode Produk</label>
      <div class="col-md-5">
        <div class="input-group">
          <input id="kode" type="text" class="form-control" name="kode" autofocus required>
          <span class="input-group-btn">
            <button onclick="showProduct()" type="button" class="btn btn-info">...</button>
          </span>
        </div>
      </div>
  </div>
</form>

<form class="form-keranjang">
{{ csrf_field() }} {{ method_field('PATCH') }}
<table class="table table-striped tabel-purchase">
<thead>
   <tr>
      <th width="30">No</th>
      <th>Kode Produk</th>
      <th>Nama Produk</th>
      <th align="right">Harga</th>
      <th>Jumlah</th>
      <th align="right">Sub Total</th>
      <th width="100">Aksi</th>
   </tr>
</thead>
<tbody></tbody>
</table>
</form>

  <div class="col-md-8">
     <div id="tampil-bayar" style="background: #dd4b39; color: #fff; font-size: 80px; text-align: center; height: 100px"></div>
     <div id="tampil-terbilang" style="background: #3c8dbc; color: #fff; font-weight: bold; padding: 10px"></div>
  </div>
  <div class="col-md-4">
    <form class="form form-horizontal form-purchase" method="post" action="{{  route('purchase.store') }} ">
      {{ csrf_field() }}
      <input type="hidden" name="idpurchase" value="{{ $idpurchase }}">
      <input type="hidden" name="total" id="total">
      <input type="hidden" name="totalitem" id="totalitem">
      <input type="hidden" name="bayar" id="bayar">

      <div class="form-group">
        <label for="totalrp" class="col-md-4 control-label">Total</label>
        <div class="col-md-8">
          <input type="text" class="form-control" id="totalrp" readonly>
        </div>
      </div>

      <div class="form-group">
        <label for="diskon" class="col-md-4 control-label">Diskon</label>
        <div class="col-md-8">
          <input type="number" class="form-control" id="diskon" name="diskon" value="0">
        </div>
      </div>

      <div class="form-group">
        <label for="bayarrp" class="col-md-4 control-label">Bayar</label>
        <div class="col-md-8">
          <input type="text" class="form-control" id="bayarrp" readonly>
        </div>
      </div>

    </form>
  </div>

      </div>
      
      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right simpan"><i class="fa fa-floppy-o"></i> Simpan Transaksi</button>
      </div>
    </div>
  </div>
</div>

@include('purchase_detail.produk')
@endsection

@section('script')
<script type="text/javascript">
var table;
$(function(){
  $('.tabel-produk').DataTable();

  table = $('.tabel-purchase').DataTable({
     "dom" : 'Brt',
     "bSort" : false,
     "processing" : true,
     "ajax" : {
       "url" : "{{ route('purchase_detail.data', $idpurchase) }}",
       "type" : "GET"
     }
  }).on('draw.dt', function(){
    loadForm($('#diskon').val());
  });


  $('.form-produk').on('submit', function(e){
      return false;
   });

   $('#kode').change(function(){
      addItem();
   });

   $('.form-keranjang').submit(function(){
     return false;
   });

   $('#diskon').change(function(){
      if($(this).val() == "") $(this).val(0).select();
      loadForm($(this).val());
   });

   $('.simpan').click(function(){
      $('.form-purchase').submit();
   });

});

function addItem(){
  $.ajax({
    url : "{{ route('purchase_detail.store') }}",
    type : "POST",
    data : $('.form-produk').serialize(),
    success : function(data){
      $('#kode').val('').focus();
      table.ajax.reload(function(){
        loadForm($('#diskon').val());
      });             
    },
    error : function(){
       alert("Tidak dapat menyimpan data!");
    }   
  });
}

function selectItem(kode){
  $('#kode').val(kode);
  $('#modal-produk').modal('hide');
  addItem();
}

function changeCount(id){
     $.ajax({
        url : "purchase_detail/"+id,
        type : "POST",
        data : $('.form-keranjang').serialize(),
        success : function(data){
          $('#kode').focus();
          table.ajax.reload(function(){
            loadForm($('#diskon').val());
          });             
        },
        error : function(){
          alert("Tidak dapat menyimpan data!");
        }   
     });
}

function showProduct(){
  $('#modal-produk').modal('show');
}

function deleteItem(id){
   if(confirm("Apakah yakin data akan dihapus?")){
     $.ajax({
       url : "purchase_detail/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload(function(){
            loadForm($('#diskon').val());
          }); 
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}

function loadForm(diskon=0){
  $('#total').val($('.total').text());
  $('#totalitem').val($('.totalitem').text());

  $.ajax({
       url : "purchase_detail/loadform/"+diskon+"/"+$('.total').text(),
       type : "GET",
       dataType : 'JSON',
       success : function(data){
         $('#totalrp').val("Rp. "+data.totalrp);
         $('#bayarrp').val("Rp. "+data.bayarrp);
         $('#bayar').val(data.bayar);
         $('#tampil-bayar').text("Rp. "+data.bayarrp);
         $('#tampil-terbilang').text(data.terbilang);
       },
       error : function(){
         alert("Tidak dapat menampilkan data!");
       }
  });
}

</script>

@endsection

resources/views/purchase_detail/produk.blade.php
<div class="modal" id="modal-produk" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title">Cari Produk</h3>
   </div>
            
<div class="modal-body">
   <table class="table table-striped tabel-produk">
      <thead>
         <tr>
            <th>Kode Produk</th>
            <th>Nama Produk</th>
            <th>Harga Beli</th>
            <th>Aksi</th>
         </tr>
      </thead>
      <tbody>
         @foreach($produk as $data)
         <tr>
            <th>{{ $data->kode_produk }}</th>
            <th>{{ $data->nama_produk }}</th>
            <th>Rp. {{ format_uang($data->harga_beli) }}</th>
            <th><a onclick="selectItem({{ $data->kode_produk }})" class="btn btn-primary"><i class="fa fa-check-circle"></i> Pilih</a></th>
          </tr>
         @endforeach
      </tbody>
   </table>

</div>
      
         </div>
      </div>
   </div>