routes/web.php
    <?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Auth;

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home1');

    Auth::routes();

    Route::group(['middleware' => ['web', 'checkAuth']], function(){
        Route::get('user/profile', 'UserController@profile')->name('user.profile');
        Route::patch('user/{id}/change', 'UserController@changeProfile');
        Route::get('user/data', 'UserController@listData')->name('user.data');
        Route::resource('user', 'UserController');

        Route::get('/home/inventory', 'HomeController@listData')->name('home.inventory');

        Route::get('transaction/new', 'SalesDetailController@newSession')->name('transaction.new');
        Route::get('transaction/{id}/data', 'SalesDetailController@listData')->name('transaction.data');
        Route::get('transaction/printnote', 'SalesDetailController@printNote')->name('transaction.print');
        Route::get('transaction/notepdf', 'SalesDetailController@notePDF')->name('transaction.pdf');
        Route::get('transaction/return', 'SalesDetailController@return')->name('transaction.return');
        Route::post('transaction/save', 'SalesDetailController@saveData');
        Route::post('transaction/wholesale', 'SalesDetailController@wholesale');
        Route::post('transaction/admincheck', 'SalesDetailController@admincheck');
        Route::post('transaction/return/{id}', 'SalesDetailController@returnID')->name('transaction.returnID');
        Route::post('transaction/returnConfirm', 'SalesDetailController@returnConfirm')->name('transaction.returnConfirm');
        Route::post('transaction/returnSubmit', 'SalesDetailController@returnSubmit')->name('transaction.returnSubmit');
        Route::post('transaction/addCustomProduct', 'SalesDetailController@addCustomProduct')->name('transaction.addCustomProduct');
        Route::get('transaction/return/{id}/data', 'SalesDetailController@returnData')->name('transaction.returnData');
        Route::get('transaction/loadform/{discount}/{total}/{received}/{id}', 'SalesDetailController@loadForm');
        Route::resource('transaction', 'SalesDetailController');
    });

    Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
        Route::get('category/data', 'CategoryController@listData')->name('category.data');
        Route::resource('category', 'CategoryController');

        Route::get('product/data', 'ProductController@listData')->name('product.data');
        Route::get('product/dataReceived', 'ProductController@listDataReceived')->name('product.data.received');
        Route::get('product/dataTransfered', 'ProductController@listDataTransfered')->name('product.data.transfered');
        Route::post('product/delete', 'ProductController@deleteSelected');
        Route::post('product/print', 'ProductController@printBarcode');
        Route::post('product/upload', 'ProductController@uploadProducts')->name('product.upload');
        Route::post('product/export', 'ProductController@exportProducts')->name('product.export');
        Route::get('product/export-inventory', 'ProductController@exportInventory')->name('product.export-inventory');
        Route::resource('product', 'ProductController');

        Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
        Route::resource('supplier', 'SupplierController');

        Route::get('member/data', 'MemberController@listData')->name('member.data');
        Route::post('member/print', 'MemberController@printCard');
        Route::resource('member', 'MemberController');

        Route::get('expenditure/data', 'ExpenditureController@listData')->name('expenditure.data');
        Route::resource('expenditure', 'ExpenditureController');

        Route::get('purchase/data', 'PurchaseController@listData')->name('purchase.data');
        Route::get('purchase/{id}/add', 'PurchaseController@create');
        Route::get('purchase/{id}/lihat', 'PurchaseController@show');
        Route::resource('purchase', 'PurchaseController');   

        Route::get('purchase_detail/{id}/data', 'PurchaseDetailController@listData')->name('purchase_detail.data');
        Route::get('purchase_detail/loadform/{diskon}/{total}', 'PurchaseDetailController@loadForm');
        Route::resource('purchase_detail', 'PurchaseDetailController');   

        Route::get('sales/data', 'SalesController@listData')->name('sales.data');
        Route::get('sales/dataReturn', 'SalesController@listDataReturn')->name('sales.dataReturn');
        Route::get('sales/{id}/show', 'SalesController@show');
        Route::resource('sales', 'SalesController');

        Route::get('reporting', 'ReportingController@index')->name('reporting.index');
        Route::post('reporting', 'ReportingController@refresh')->name('reporting.refresh');
        Route::get('reporting/data/{start}/{end}', 'ReportingController@listData')->name('reporting.data'); 
        Route::get('reporting/pdf/{start}/{end}', 'ReportingController@exportPDF');

        Route::resource('setting', 'SettingController');

        Route::get('receiving/data', 'ReceivingController@listData')->name('receiving.data');
        Route::post('receiving/new', 'ReceivingController@newSession')->name('receiving.new');
        Route::post('receiving/clear', 'ReceivingController@clearSession')->name('receiving.clear');
        Route::resource('receiving', 'ReceivingController');

        Route::get('transfer/data', 'TransferController@listData')->name('transfer.data');
        Route::get('transfer/newData', 'TransferController@listNewData')->name('transfer.newData');
        Route::post('transfer/new', 'TransferController@newSession')->name('transfer.new');
        Route::get('transfer/notepdf', 'TransferController@notePDF')->name('transfer.pdf');
        Route::any('transfer/clearSession', 'TransferController@clearSession')->name('transfer.clearSession');
        Route::resource('transfer', 'TransferController');

        Route::get('branch/data', 'BranchController@listData')->name('branch.data');
        Route::resource('branch', 'BranchController');
    });

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $table = 'supplier';
    protected $primaryKey = 'supplier_id';

    public function purchase(){
        return $this->hasMany('App\Purchase', 'supplier_id');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('supplier.index'); 
    }

    public function listData()
    {
        $supplier = Supplier::orderBy('supplier_id', 'desc')->get();
        $no = 0;
        $data = array();
        foreach($supplier as $list){
            $no ++;
            $row = array();
            $row[] = $no;
            $row[] = $list->name;
            $row[] = $list->address;
            $row[] = $list->phone;
            $row[] = '<div class="btn-group">
                    <a onclick="editForm('.$list->supplier_id.')" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                    <a onclick="deleteData('.$list->supplier_id.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a></div>';
            $data[] = $row;
        }

        $output = array("data" => $data);
        return response()->json($output);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $supplier = new Supplier;
        $supplier->name   = $request['name'];
        $supplier->address = $request['address'];
        $supplier->phone = $request['phone'];
        $supplier->save();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::find($id);
        echo json_encode($supplier);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);
        $supplier->name = $request['name'];
        $supplier->address = $request['address'];
        $supplier->phone = $request['phone'];
        $supplier->update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        $supplier->delete();
    }
}

resources/views/supplier/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
   <form class="form-horizontal" data-toggle="validator" method="post">
   {{ csrf_field() }} {{ method_field('POST') }}
   
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title"></h3>
   </div>
            
<div class="modal-body">
   
   <input type="hidden" id="id" name="id">
   <div class="form-group">
      <label for="name" class="col-md-3 control-label">Name</label>
      <div class="col-md-6">
         <input id="name" type="text" class="form-control" name="name" autofocus required>
         <span class="help-block with-errors"></span>
      </div>
   </div>

   <div class="form-group">
      <label for="address" class="col-md-3 control-label">Address</label>
      <div class="col-md-8">
         <input id="address" type="text" class="form-control" name="address" required>
         <span class="help-block with-errors"></span>
      </div>
   </div>

   <div class="form-group">
      <label for="phone" class="col-md-3 control-label">Phone</label>
      <div class="col-md-6">
         <input id="phone" type="number" class="form-control" name="phone" autofocus required>
         <span class="help-block with-errors"></span>
      </div>
   </div>
   
</div>
   
   <div class="modal-footer">
      <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Save </button>
      <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Cancel</button>
   </div>
      
   </form>

         </div>
      </div>
   </div>

resources/views/supplier/index.blade.php
@extends('layouts.app')

@section('title')
  Supplier List
@endsection

@section('breadcrumb')
   @parent
   <li>supplier</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add Supplier</a>
      </div>
      <div class="box-body">  

<table class="table table-striped">
<thead>
   <tr>
      <th width="30">No</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th width="100">Action</th>
   </tr>
</thead>
<tbody></tbody>
</table>

      </div>
    </div>
  </div>
</div>

@include('supplier.form')
@endsection

@section('script')
<script type="text/javascript">
var table, save_method;
$(function(){
   table = $('.table').DataTable({
     "processing" : true,
     "ajax" : {
       "url" : "{{ route('supplier.data') }}",
       "type" : "GET"
     }
   }); 
   
   $('#modal-form form').validator().on('submit', function(e){
      if(!e.isDefaultPrevented()){
         var id = $('#id').val();
         if(save_method == "add") url = "{{ route('supplier.store') }}";
         else url = "supplier/"+id;
         
         $.ajax({
           url : url,
           type : "POST",
           data : $('#modal-form form').serialize(),
           success : function(data){
             $('#modal-form').modal('hide');
             table.ajax.reload();
           },
           error : function(){
             alert("Error in Save");
           }   
         });
         return false;
     }
   });
});

function addForm(){
   save_method = "add";
   $('input[name=_method]').val('POST');
   $('#modal-form').modal('show');
   $('#modal-form form')[0].reset();            
   $('.modal-title').text('Add Supplier');
}

function editForm(id){
   save_method = "edit";
   $('input[name=_method]').val('PATCH');
   $('#modal-form form')[0].reset();
   $.ajax({
     url : "supplier/"+id+"/edit",
     type : "GET",
     dataType : "JSON",
     success : function(data){
       $('#modal-form').modal('show');
       $('.modal-title').text('Edit Supplier');
       
       $('#id').val(data.supplier_id);
       $('#name').val(data.name);
       $('#address').val(data.address);
       $('#phone').val(data.phone);
       
     },
     error : function(){
       alert("Error in edit");
     }
   });
}

function deleteData(id){
   if(confirm("Are you sure you want to delete supplier?")){
     $.ajax({
       url : "supplier/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload();
       },
       error : function(){
         alert("Error in deletions");
       }
     });
   }
}
</script>
@endsection